/*
 * File: app/store/CheckMessageStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Google.store.CheckMessageStore', {
    extend: 'Ext.data.Store',
    alias: 'store.CheckMessageStore',

    requires: [
        'Google.model.CheckMessages'
    ],

    config: {
        model: 'Google.model.CheckMessages',
        storeId: 'CheckMessageStore',
        proxy: {
            type: 'ajax',
            url: 'http://api.eventsy.co.uk/message-service.php',
            reader: {
                type: 'json'
            }
        }
    }
});