/*
 * File: app/store/LocalVenues.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Google.store.LocalVenues', {
    extend: 'Ext.data.Store',
    alias: 'store.LocalVenues',

    requires: [
        'Google.model.LocalVenues'
    ],

    config: {
        data: [
            {
                id: '1',
                title: 'Champneys Tiring',
                address_1: 'Lewings Farm, Chesham Road',
                address_2: 'Wiginton, Tiring, Hertfordshire',
                postcode: 'HP23 6HY',
                tel: '01442 291 000',
                lat: '51.769314',
                long: '-0.62813',
                event_id: '1'
            }
        ],
        model: 'Google.model.LocalVenues',
        storeId: 'LocalVenues'
    }
});