/*
 * File: app/store/ScheduleDay3.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Google.store.ScheduleDay3', {
    extend: 'Ext.data.Store',

    requires: [
        'Google.model.Schedule'
    ],

    config: {
        model: 'Google.model.Schedule',
        storeId: 'ScheduleDay3',
        proxy: {
            type: 'ajax',
            url: 'http://api.eventsy.co.uk/web-service.php?agenda=true&day=2013-05-22&event=1',
            reader: {
                type: 'json',
                rootProperty: 'categories'
            }
        }
    }
});