/*
 * File: app/view/CreativeList.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Google.view.CreativeList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.CreativeList',

    config: {
        id: 'CreativeList',
        itemId: 'CreativeList',
        store: 'SandboxStore',
        itemTpl: [
            '<div class="CreativeSandboxPadding">',
            '    <div class="CreativeSandboxLeft">',
            '        <img src="{icon}" />',
            '    </div>',
            '    ',
            '    <div class="CreativeSandboxRight">',
            '    ',
            '        <div class="CreativeSandboxTitle">{title}</div>',
            '        <div class="CreativeSandboxInfo"><small>{info}</small></div>',
            '    ',
            '    </div>',
            '</div>'
        ],
        listeners: [
            {
                fn: 'onListInitialize',
                event: 'initialize'
            },
            {
                fn: 'onCreativeListItemTap',
                event: 'itemtap'
            }
        ]
    },

    onListInitialize: function(component, options) {
        // Load in the stores


        //Load the Speakers Store in
        Ext.getStore('SandboxStore').load();
    },

    onCreativeListItemTap: function(dataview, index, target, record, e, options) {
        this.up('NavView').push({
            xtype: 'SandboxDetails',
            data: record.data,
            title: 'Details'
        });
    }

});