/*
 * File: app/view/Dashboard.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Google.view.Dashboard', {
    extend: 'Ext.Panel',
    alias: 'widget.Dashboard',

    config: {
        padding: 20,
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'button',
                height: 60,
                itemId: 'mybutton1',
                text: 'MyButton1'
            }
        ],
        listeners: [
            {
                fn: 'onMybutton1Tap',
                event: 'tap',
                delegate: '#mybutton1'
            }
        ]
    },

    onMybutton1Tap: function(button, e, options) {
        this.up('Main').push({
            title: 'Agenda',
            xtype: 'Schedule'
        });
    }

});