/*
 * File: app/view/EventDetailView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Google.view.EventDetailView', {
    extend: 'Ext.Panel',
    alias: 'widget.EventDetailView',

    config: {
        itemId: 'EventDetailView',
        padding: 10,
        tpl: [
            '<large>{title}</large>',
            '',
            '<br />',
            '',
            'Date: {date:date("l, M d Y")}<br />',
            'Time: {time} - {until}<br />',
            'Location: {location}',
            '',
            '<div class="blue-bar-small">',
            '    ',
            '    Description',
            '    ',
            '</div>',
            '',
            '{description}',
            '',
            '',
            '',
            '<div class="blue-bar-small">',
            '    ',
            '    Speakers',
            '    ',
            '</div>',
            '<div id="speakers-box">',
            '<div class="spacing">',
            '    ',
            '    ',
            '    {speaker_id}',
            '    ',
            '</div>',
            '    ',
            '</div>'
        ],
        listeners: [
            {
                fn: 'onEventDetailViewShow',
                event: 'show'
            },
            {
                fn: 'onEventDetailViewInitialize',
                event: 'initialize'
            }
        ]
    },

    onEventDetailViewShow: function(component, options) {
        //Ext.getCmp('AskQuestionButton').show(true);


        var record = this.getData();


        Ext.getCmp('AskQuestionButton').config.EventID = record.id;
    },

    onEventDetailViewInitialize: function(component, options) {
        Ext.getCmp('AskQuestionButton').show(true);
    }

});