/*
 * File: app/view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Google.view.LoginPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.LoginPanel',

    requires: [
        'Ext.field.Text',
        'Ext.field.Password',
        'Ext.MessageBox'
    ],

    config: {
        refs: '#loginform',
        id: 'loginform',
        itemId: 'loginform',
        items: [
            {
                xtype: 'container',
                html: 'Welcome to Zeitgeist 2013.<br /><br /> <small>To proceed you must have a valid username and password sent to you in your welcome email.</small>',
                padding: 10,
                style: 'margin-bottom:20px;'
            },
            {
                xtype: 'textfield',
                style: 'border-radius:10px;',
                label: 'User',
                name: 'username'
            },
            {
                xtype: 'passwordfield',
                style: 'margin-top:20px; border-radius:10px;',
                label: 'Pass',
                name: 'password'
            },
            {
                xtype: 'button',
                itemId: 'submitLoginForm',
                style: 'margin-top:20px;',
                ui: 'confirm',
                text: 'Login'
            }
        ],
        listeners: [
            {
                fn: 'submitLoginForm',
                event: 'tap',
                delegate: '#submitLoginForm'
            }
        ]
    },

    submitLoginForm: function(button, e, options) {
        var values = this.getValues();

        this.submit({
            url: 'http://192.168.0.12:8888/web/checkLogin.php',
            method: 'POST',
            success: function(response) {
                // do whatever you need to with the generated HTML
                //window.location = 'app.html';
                //this.up('Main').push({ title: 'Dashboard', xtype: 'Dashboard'});


                Ext.Viewport.setActiveItem('Main');

            },
            failure: function(response){
                // Do failure message
                Ext.Msg.alert('Login Failed', "Sorry, we couldn't log you in. Please check your details and try again.");
            }
        });
    }

});