/*
 * File: app/view/NavView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Google.view.NavView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.NavView',

    requires: [
        'Google.view.Dashboard'
    ],

    config: {
        id: 'NavView',
        itemId: 'NavView',
        items: [
            {
                xtype: 'Dashboard'
            }
        ],
        navigationBar: {
            style: 'background-color:#000;',
            items: [
                {
                    xtype: 'button',
                    align: 'left',
                    id: 'SettingsButton',
                    itemId: 'SettingsButton',
                    iconCls: 'settings',
                    iconMask: true
                },
                {
                    xtype: 'button',
                    align: 'right',
                    hidden: true,
                    id: 'AskQuestionButton',
                    itemId: 'AskQuestionButton',
                    ui: 'confirm',
                    iconAlign: 'right',
                    text: 'Ask Question'
                }
            ]
        },
        listeners: [
            {
                fn: 'onMybutton11Tap',
                event: 'tap',
                delegate: '#SettingsButton'
            },
            {
                fn: 'onAskQuestionButtonTap',
                event: 'tap',
                delegate: '#AskQuestionButton'
            }
        ]
    },

    onMybutton11Tap: function(button, e, options) {
        this.push({
            title: 'Settings',
            xtype: 'SettingsPanel'
        });


        // Hide Settings, Logout and Messages buttons

        Ext.getCmp('MessageButton').hide(true);
        Ext.getCmp('SettingsButton').hide(true);
    },

    onAskQuestionButtonTap: function(button, e, options) {
        // Go to the Ask A Question panel and try to include the specific id of the event it was pressed on
        var test = button.getInitialConfig('EventID');

        Ext.getCmp('NavView').push({
            xtype: 'AskQuestion',
            title: 'Details',
            EventID: test
        });

        console.log(test);
    }

});