/*
 * File: app/view/ProfileDetails.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Google.view.ProfileDetails', {
    extend: 'Ext.Panel',
    alias: 'widget.profileDetails',

    config: {
        padding: 10,
        scrollable: 'vertical',
        tpl: [
            '<div class="profile-top-info">',
            '    ',
            '    <div class="speakerImage">',
            '        <img src="{image}" />',
            '    </div>',
            '    ',
            '    <div class="profile-top-details">',
            '        {full_name} <br />',
            '        {quick_bio}',
            '    </div>',
            '</div>',
            '',
            '<div class="profile-bio">',
            '    ',
            '    <div class="blue-bar-small">',
            '    ',
            '        Bio',
            '    ',
            '    </div>',
            '        <div class="bio-full">',
            '            <div class="width-change">',
            '                {bio}',
            '            </div>',
            '        </div>',
            '            ',
            '        ',
            '        <br />',
            '        <br />',
            '        <a target="_blank" href="{web_address}">{web_address}</a>',
            '',
            '',
            '    <div class="blue-bar-small">',
            '    ',
            '        Events',
            '    ',
            '    </div>',
            '',
            '',
            '</div>'
        ]
    }

});