/*
 * File: app/view/VenueList.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Google.view.VenueList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.VenueList',

    config: {
        store: 'LocalVenues',
        itemTpl: [
            '<div>',
            '    <div class="attendee-name">{title}</div>',
            '    <small>{address_1}</small><br />',
            '    <small>{address_2}</small>',
            '</div>'
        ],
        listeners: [
            {
                fn: 'onListInitialize',
                event: 'initialize'
            },
            {
                fn: 'onListItemTap',
                event: 'itemtap'
            }
        ]
    },

    onListInitialize: function(component, options) {
        // Load in the stores


        //Load the Speakers Store in
        Ext.getStore('LocalVenues').load();
    },

    onListItemTap: function(dataview, index, target, record, e, options) {
        this.up('NavView').push({
            xtype: 'VenueDetailView',
            data: record.data,
            title: 'Details'
        });
    }

});