/*
 * File: app/view/VenueDetailView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Google.view.VenueDetailView', {
    extend: 'Ext.Panel',
    alias: 'widget.VenueDetailView',

    requires: [
        'Ext.Map',
        'Ext.Label'
    ],

    config: {
        listeners: [
            {
                fn: 'onPanelInitialize',
                event: 'initialize'
            },
            {
                fn: 'onVenueTelTap',
                event: 'tap',
                delegate: '#VenueTel'
            }
        ],
        items: [
            {
                xtype: 'container',
                height: '40%',
                itemId: 'VenueInformation',
                padding: 20,
                items: [
                    {
                        xtype: 'label',
                        html: 'Title',
                        id: 'VenueTitle',
                        itemId: 'VenueTitle',
                        style: ' font-size:32px; color:#1a6eb6; '
                    },
                    {
                        xtype: 'label',
                        id: 'VenueAddress',
                        itemId: 'VenueAddress'
                    },
                    {
                        xtype: 'button',
                        id: 'VenueTel',
                        itemId: 'VenueTel',
                        ui: 'confirm',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'map',
                height: '60%',
                itemId: 'VenueMap'
            }
        ]
    },

    onPanelInitialize: function(component, options) {
        var record = this.getData();


        mapView = this.child('#VenueMap');

        //lat = record.get('latitude');
        //lon = record.get('longitude');

        mapView.setMapOptions({
            zoom: 12
        });


        var myLatLng = new google.maps.LatLng(record.lat,record.long);

        mapView.setMapCenter({
            latitude: record.lat,
            longitude: record.long
        });


        marker = new google.maps.Marker({
            title: record.title,
            position: myLatLng
        });

        marker.setMap(mapView.getMap()); //or myMap.map or this.getMap()



        console.log(record);


        Ext.getCmp('VenueTitle').setHtml(record.title);
        Ext.getCmp('VenueAddress').setHtml(record.address_1 + '<br />' + record.address_2 + '<br />' + record.postcode);


        Ext.getCmp('VenueTel').setText(record.tel);
    },

    onVenueTelTap: function(button, e, options) {
        Ext.Msg.alert("WIP", "This function has not been implemented yet.");
    }

});