/*
 * File: app/model/AttendeesList.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Google.model.AttendeesList', {
    extend: 'Ext.data.Model',
    alias: 'model.AttendeesList',

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'full_name'
            },
            {
                name: 'company'
            },
            {
                name: 'j_title'
            },
            {
                name: 'event_id'
            },
            {
                name: 'allow_messaging'
            },
            {
                name: 'staff'
            }
        ]
    }
});