/*
 * File: app/model/LocalVenues.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Google.model.LocalVenues', {
    extend: 'Ext.data.Model',
    alias: 'model.LocalVenues',

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'title'
            },
            {
                name: 'address_1'
            },
            {
                name: 'address_2'
            },
            {
                name: 'postcode'
            },
            {
                name: 'tel'
            },
            {
                name: 'long'
            },
            {
                name: 'lat'
            }
        ]
    }
});