/*
 * File: app/model/MessageList.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Google.model.MessageList', {
    extend: 'Ext.data.Model',
    alias: 'model.MessageList',

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'user_id'
            },
            {
                name: 'subject'
            },
            {
                name: 'message'
            },
            {
                name: 'receipt'
            },
            {
                name: 'date'
            },
            {
                name: 'recipient'
            },
            {
                name: 'username'
            },
            {
                name: 'c_id'
            }
        ]
    }
});